#!/usr/bin/env python3
"""
hotspot_interface.py – Generate HotSpot thermal-simulation input files from
HNOCS simulation results.

Outputs:
  hotspot.flp           – floorplan (unit positions and sizes)
  hotspot_power.trace   – per-time-step power for every unit
  hotspot.config        – HotSpot run-time configuration

Usage:
    python3 hotspot_interface.py [--pes N] [--trace power_trace.csv]

Then run HotSpot:
    hotspot -c hotspot.config -f hotspot.flp -p hotspot_power.trace \
            -o hotspot_temp.trace
"""

import argparse
import math
import os
import sys


# ---------------------------------------------------------------------------
# Floorplan
# ---------------------------------------------------------------------------

def generate_floorplan(num_pes, num_routers, output_file):
    """
    Write a HotSpot floorplan file.

    Layout: PEs and routers are arranged on a square grid.  Each PE occupies
    a 1 mm × 1 mm cell; each router occupies a 0.5 mm × 0.5 mm cell placed
    at the upper-right corner of its corresponding PE cell.

    Format per line:
        <unit-name>  <width_m>  <height_m>  <left_x_m>  <bottom_y_m>
    """
    cols = int(math.ceil(math.sqrt(num_pes)))
    rows = math.ceil(num_pes / cols)
    pe_size   = 0.001     # 1 mm
    cell_pitch = pe_size * 1.5

    with open(output_file, 'w') as f:
        f.write("# HotSpot Floorplan generated by HNOCS hotspot_interface.py\n")
        f.write("# <unit-name>\t<width>\t<height>\t<left-x>\t<bottom-y>\n")

        for i in range(num_pes):
            row = i // cols
            col = i % cols
            x = col * cell_pitch
            y = row * cell_pitch
            f.write(f"PE{i}\t{pe_size:.6f}\t{pe_size:.6f}\t{x:.6f}\t{y:.6f}\n")

        router_size = pe_size * 0.5
        for i in range(num_routers):
            row = i // cols
            col = i % cols
            x = col * cell_pitch + pe_size
            y = row * cell_pitch + pe_size
            f.write(f"Router{i}\t{router_size:.6f}\t{router_size:.6f}"
                    f"\t{x:.6f}\t{y:.6f}\n")

    print(f"Floorplan saved to {output_file}")


# ---------------------------------------------------------------------------
# Power trace conversion
# ---------------------------------------------------------------------------

def parse_hnocs_trace(trace_file, num_pes, sample_interval=1e-6):
    """
    Read an HNOCS CSV power trace and resample it into fixed time steps.

    Returns a list of (pe_power_list, router_power_list) tuples, one per
    time step.
    """
    if not os.path.isfile(trace_file):
        print(f"Warning: trace file not found ({trace_file}); "
              "using placeholder data.")
        return None

    # Collect per-PE instantaneous power keyed by time bucket
    import collections
    pe_power_at = collections.defaultdict(dict)   # time_bucket -> {pe_id: power}

    with open(trace_file) as fh:
        header = None
        for line in fh:
            line = line.strip()
            if not line:
                continue
            parts = line.split(',')
            if header is None:
                header = parts
                continue
            row = dict(zip(header, parts))
            if row.get('ComponentType') != 'PE':
                continue
            try:
                t_ns  = float(row['Time(ns)'])
                pe_id = int(row['ComponentID'])
                value = float(row['Value'])
            except (KeyError, ValueError):
                continue
            bucket = int(t_ns * 1e-9 / sample_interval)
            pe_power_at[bucket][pe_id] = value

    if not pe_power_at:
        return None

    max_bucket = max(pe_power_at.keys())
    steps = []
    for b in range(max_bucket + 1):
        pe_p = [pe_power_at[b].get(i, 0.1) for i in range(num_pes)]
        # Routers: simple estimate = 20 % of average PE power
        avg_pe = sum(pe_p) / len(pe_p) if pe_p else 0.1
        router_p = [avg_pe * 0.2] * num_pes
        steps.append((pe_p, router_p))

    return steps


def generate_placeholder_trace(num_pes, num_routers, time_steps=1000):
    """Generate synthetic power data when no real trace is available."""
    import random
    steps = []
    for _ in range(time_steps):
        pe_p     = [random.uniform(0.5, 2.5) for _ in range(num_pes)]
        router_p = [random.uniform(0.2, 1.0) for _ in range(num_routers)]
        steps.append((pe_p, router_p))
    return steps


def write_hotspot_power_trace(steps, num_pes, num_routers, output_file):
    """Write the HotSpot power trace (one row per time step)."""
    with open(output_file, 'w') as f:
        f.write("# HotSpot power trace: "
                f"{num_pes} PEs + {num_routers} Routers per row\n")
        for pe_p, router_p in steps:
            values = [f"{v:.4f}" for v in pe_p] + [f"{v:.4f}" for v in router_p]
            f.write(" ".join(values) + "\n")
    print(f"HotSpot power trace saved to {output_file}")


# ---------------------------------------------------------------------------
# HotSpot configuration
# ---------------------------------------------------------------------------

def generate_hotspot_config(output_file, sample_interval=1e-6):
    """Write a minimal HotSpot configuration file."""
    config = f"""\
# HotSpot Configuration generated by HNOCS hotspot_interface.py
-t_chip              0.00050
-s_chip              0.01500
-s_sink              0.06000
-t_sink              0.00050
-t_interface         0.00005
-thermal_threshold   354.95
-model_type          grid
-grid_rows           64
-grid_cols           64
-sampling_intvl      {sample_interval:.2e}
-base_proc_freq      1e9
-dtm_used            0
"""
    with open(output_file, 'w') as f:
        f.write(config)
    print(f"HotSpot config saved to {output_file}")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Generate HotSpot input files from HNOCS simulation results.")
    parser.add_argument("--pes",      type=int, default=16,
                        help="Number of PEs (default: 16)")
    parser.add_argument("--trace",    default="",
                        help="HNOCS power trace CSV (optional)")
    parser.add_argument("--interval", type=float, default=1e-6,
                        help="Sampling interval in seconds (default: 1e-6)")
    args = parser.parse_args()

    num_pes     = args.pes
    num_routers = num_pes   # one router per PE in a mesh

    # Floorplan
    generate_floorplan(num_pes, num_routers, "hotspot.flp")

    # Power trace
    steps = None
    if args.trace:
        steps = parse_hnocs_trace(args.trace, num_pes, args.interval)
    if steps is None:
        print("Generating placeholder power trace data.")
        steps = generate_placeholder_trace(num_pes, num_routers)

    write_hotspot_power_trace(steps, num_pes, num_routers, "hotspot_power.trace")

    # Config
    generate_hotspot_config("hotspot.config", args.interval)

    print("\nTo run HotSpot thermal simulation:")
    print("  hotspot -c hotspot.config -f hotspot.flp "
          "-p hotspot_power.trace -o hotspot_temp.trace")


if __name__ == "__main__":
    main()
